# Generated by Django 5.2.8 on 2026-07-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_details', '0002_soft_delete_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=128)),
                ('dc_ips', models.TextField()),
                ('dc_ports', models.TextField()),
                ('dc_ha_ips', models.TextField()),
                ('dc_ha_ports', models.TextField()),
                ('dr_ips', models.TextField()),
                ('dr_ports', models.TextField()),
                ('dr_ha_ips', models.TextField()),
                ('dr_ha_ports', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cluster_details',
            },
        ),
    ]
