# Generated by Django 5.2.8 on 2026-08-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('db_details', '0003_clusterdetails'), ('db_details', '0004_clusterdetails_db_name_clusterdetails_db_password'), ('db_details', '0005_clusterdetails_server_password_and_more'), ('db_details', '0006_clusterdetails_arbiter_ips_and_more'), ('db_details', '0007_clusterdetails_db_username'), ('db_details', '0008_clusterdetails_auth_mechanism')]

    dependencies = [
        ('db_details', '0002_soft_delete_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_type', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=128)),
                ('dc_ips', models.TextField()),
                ('dc_ports', models.TextField()),
                ('dc_ha_ips', models.TextField()),
                ('dc_ha_ports', models.TextField()),
                ('dr_ips', models.TextField()),
                ('dr_ports', models.TextField()),
                ('dr_ha_ips', models.TextField()),
                ('dr_ha_ports', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('db_name', models.CharField(default='', max_length=128)),
                ('db_password', models.TextField(default='')),
                ('server_password', models.TextField(default='')),
                ('server_username', models.CharField(default='', max_length=128)),
                ('arbiter_ips', models.TextField(blank=True, default='')),
                ('arbiter_ports', models.TextField(blank=True, default='')),
                ('db_username', models.CharField(default='', max_length=128)),
                ('auth_mechanism', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'cluster_details',
            },
        ),
    ]
