# Generated by Django 5.2.8 on 2026-07-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_details', '0003_clusterdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterdetails',
            name='db_name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='clusterdetails',
            name='db_password',
            field=models.TextField(default=''),
        ),
    ]
