# Generated by Django 5.2.8 on 2026-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_details', '0004_clusterdetails_db_name_clusterdetails_db_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterdetails',
            name='server_password',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='clusterdetails',
            name='server_username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
