# Generated by Django 5.2.8 on 2026-07-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_details', '0005_clusterdetails_server_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterdetails',
            name='arbiter_ips',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clusterdetails',
            name='arbiter_ports',
            field=models.TextField(blank=True, default=''),
        ),
    ]
