# Generated by Django 5.2.8 on 2026-07-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_details', '0006_clusterdetails_arbiter_ips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterdetails',
            name='db_username',
            field=models.CharField(default='', max_length=128),
        ),
    ]
