# Generated by Django 5.2.8 on 2026-07-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_details', '0007_clusterdetails_db_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterdetails',
            name='auth_mechanism',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
