# Generated by Django 5.2.8 on 2026-08-07 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_details', '0008_clusterdetails_auth_mechanism'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128)),
                ('cluster_name', models.CharField(max_length=128)),
                ('status', models.CharField(default='running', max_length=32)),
                ('deploy_parameters', models.JSONField(default=dict)),
                ('log_output', models.TextField(default='')),
                ('result_html', models.TextField(default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='db_details.clusterdetails')),
            ],
            options={
                'db_table': 'deployment_results',
                'ordering': ['-started_at'],
            },
        ),
    ]
